### ISSUE TITLE
Need to change the contents 

### ISSUE THREAD

**Issue by AFEEF12345** [AFEEF12345/Ecomm2#1]
bug

**Comment by KarishmaVanwari** [comment]
Hey @AFEEF12345  could you please elaborate as to what content is to be changed?

**Comment by AFEEF12345** [comment]
some contents in the code  and fix some bugs in the code

**Comment by AFEEF12345** [comment]
you can change the content in the website .and bring attractive

**Comment by AFEEF12345** [comment]
k
